version: "3.1"
services:

  discovery-service:
    container_name: poliChess-discovery-service
    build:
      dockerfile: Dockerfile
      context: ./service-discovery

  user-service:
    container_name: poliChess-user-service
    build:
      dockerfile: Dockerfile
      context: ./user-service
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    links:
      - mongo
      - discovery-service

  mongo:
    container_name: poliChess-mongo
    image: mongo
    volumes:
      - ~/data/mongo:/data/db
    command: mongod --quiet --logpath /dev/null


  matchmaking-service:
    container_name: poliChess-matchmaking-service
    build:
      dockerfile: Dockerfile
      context: ./matchmaking-service
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    links:
      - postgres
      - discovery-service

  postgres:
    container_name: poliChess-postgres
    image: postgres:14-alpine
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    command: postgres -c stats_temp_directory=/tmp


  game-engine-service:
    container_name: poliChess-game-engine-service
    build:
      dockerfile: Dockerfile
      context: ./game-engine-service
    environment:
      - NODE_ENV=production
    links:
      - discovery-service


  redis:
    container_name: poliChess-redis
    image: redis
    volumes:
      - ~/data/redis:/data


  websocket-server:
    container_name: poliChess-websocket-server
    build:
      dockerfile: Dockerfile
      context: ./websocket-server
    environment:
      - NODE_ENV=production
    ports:
      - 3001:8080
    links:
      - discovery-service
      - redis
      - game-engine-service
      - matchmaking-service


  api-gateway:
    container_name: poliChess-api-gateway
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    links:
      - discovery-service
      - redis
      - user-service
      - matchmaking-service
      - game-engine-service


  frontend:
    container_name: poliChess-frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      - NODE_ENV=production
      - REACT_APP_API=192.168.0.105
    ports:
      - 3002:3000
